In [4]:
import pandas as pd
digit_train = pd.read_csv('digit_train.csv')
digit_train.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [11]:
train_x = digit_train[digit_train.columns[1:]].as_matrix()
train_y = digit_train.label.as_matrix()

In [38]:
from scipy.spatial.distance import cdist
sample = train_x[:100]
cdist(train_x, sample, 'euclidean')

array([[    0.        ,  3307.63873481,  2217.55225418, ...,
         2927.01622818,  2749.91490777,  3091.66815813],
       [ 3307.63873481,     0.        ,  3224.55206191, ...,
         2674.49808375,  3066.37179742,  2924.55329922],
       [ 2217.55225418,  3224.55206191,     0.        , ...,
         2891.44600503,  2787.82818696,  3079.28498194],
       ..., 
       [ 3020.53124467,  2926.08424349,  2698.30335581, ...,
         2852.40267143,  2970.06144718,  3206.62143073],
       [ 2888.25968362,  3000.85521144,  2344.02687698, ...,
         2872.97058808,  2532.8174036 ,  2859.51184645],
       [ 2177.98002746,  3094.40802093,  2276.27436835, ...,
         2877.62558371,  2798.85565901,  3186.34163266]])

In [32]:
sample.reshape(1,-1).shape

(1, 784)

In [22]:
a = digit_train.as_matrix()[:5, :5]
a

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
a - a[2,]

array([[ 0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0]])